vorzimmer_licht_timer_off_abend:
    alias: "Vorzimmer Timer aus (Abend)"
    sequence:
     - delay: '00:{{ states.input_slider.licht_dauer_abend.state | int}}:00'
     - service: homeassistant.turn_off
       entity_id: 
        - light.vorzimmer_2
        - light.kleiderstaender        
        - light.lumibar        
     - delay: '00:00:01'
     - service: homeassistant.turn_off
       entity_id: 
        - light.vorzimmer_2
        - light.kleiderstaender        
        - light.lumibar
