  - alias: Fernsehen
    trigger:
      - platform: state
        entity_id: media_player.lg_tv_remote
        to: 'playing'
    condition:
       condition: sun
       after: sunset
    action:
       service: scene.turn_on  
       entity_id: scene.fernsehlicht
