  - alias: Guten Morgen
    trigger:
      - platform: state
        entity_id: media_player.bose
        to: 'playing'
    condition:
       condition: time
       after:  '05:00:00'
       before: '08:00:00' 
    action:
       service: homeassistant.turn_on  
       entity_id: script.guten_morgen
       
