  - alias: "Alle weg"
    trigger: 
     - platform: state
       entity_id: device_tracker.christian, device_tracker.peter
       from: 'not_home'
       to: 'home'
    condition:
       - condition: time
         after: '15:30:00'
         before: '19:00:00'
          weekday: 
            - tue
    action:
       service: homeassistant.turn_on
       entity_id: script.licht_putzfrau_ende