  vorzimmer_putzfrau_startzeit:
     name: "Putzfrau kommen"
     options:
       - "14:00"
       - "14:15"
       - "14:30"
       - "14:45"
       - "15:00"
       - "15:15"
       - "15:30"
       - "15:45"
       - "16:00"
       - "16:15"
       - "16:30"
       - "16:45"
       - "17:00"
       - "17:15"
       - "17:30"
       - "17:45"
     initial: "15:00"
