  vorzimmer_putzfrau_endzeit:
     name: "Putzfrau gehen"
     options:
       - "17:00"
       - "17:15"
       - "17:30"
       - "17:45"
       - "18:00"
       - "18:15"
       - "18:30"
       - "18:45"
       - "19:00"
       - "19:15"
       - "19:30"
       - "19:45"
       - "20:00"
       - "20:15"
       - "20:30"
       - "20:45"
     initial: "19:00"
