  vorzimmer_nacht_startzeit:
     name: "Zeit Nacht"
     options:
       - "20:00"
       - "20:30"
       - "21:00"
       - "21:30"
       - "22:00"
       - "22:30"
       - "23:00"
       - "23:30"
     initial: "22:00"
